### ISSUE TITLE
Module file was created by an older version of the compiler

### ISSUE THREAD

**Issue by aleiku** [joedemo/BeaconFramework_demo#1]
Hi 我用Xcode 7.3在build時會出現這個訊息。

請問怎麼處理呢？

.../BeaconFramework_demo/Global.swift:10:8: Module file was created by an older version of the compiler; rebuild 'BeaconFramework' and try again: .../BeaconFramework.framework/Modules/BeaconFramework.swiftmodule/arm64.swiftmodule

**Comment by joedemo** [comment]
你好, 已新增 swift 2.3 版支援（branch swift2.3）

**Comment by joedemo** [comment]
Hi, framework更新 (支援universal framework ; device or simulator 環境皆可執行)

**Comment by aleiku** [comment]
感謝 已收到。
