### ISSUE TITLE
upload上App Store時出現Unsupported Architectures。

### ISSUE THREAD

**Issue by aleiku** [joedemo/BeaconFramework_demo#2]
Hi 我要upload to App Store時出現以下訊息

ERROR ITMS-90087: "Unsupported Architectures. The executable for /Frameworks/BeaconFramework.framework contains unsupported architectures '[x86_64, i386]'."
ERROR ITMS-90087: "Unsupported Architectures. The executable for /Frameworks/BeaconFramework.framework contains unsupported architectures '[x86_64, i386]'."

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at '/Frameworks/BeaconFramework.framework/BeaconFramework' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at '/Frameworks/BeaconFramework.framework/BeaconFramework' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

**Comment by joedemo** [comment]
hi~ 提供實機  framework 檔案
請解壓後更名為BeaconFramework.framework

https://github.com/joedemo/BeaconFramework_demo/blob/swift2.3/BeaconFramework(實機).framework.zip?raw=true
