### ISSUE TITLE
compile error with Xcode7.3

### ISSUE THREAD

**Issue by loganLiou** [joedemo/BeaconFramework_demo#3]
Hi,
I am trying to build this demo app, but got a compile error of the following error message,
/Users/<myuser>/workspace/BeaconFramework_demo/BeaconFramework_demo/AppDelegate.swift:10:8: error: module file was created by an older version of the compiler; rebuild 'BeaconFramework' and try again: /Users/<myuser>/workspace/BeaconFramework_demo/BeaconFramework.framework/Modules/BeaconFramework.swiftmodule/arm64.swiftmodule
import BeaconFramework
Can you help?
I am using Xcode7.3,
thanks~

**Comment by joedemo** [comment]
Hi, Please build this demo app with swift2.3 branch 
thanks~

**Comment by loganLiou** [comment]
It works, thanks!
